### ISSUE TITLE
hostNetwork support in helm chart

### ISSUE THREAD

**Issue by mrfelek** [CloudHealth/helm#121]
Hello,
Please add "hostNetwork" parameter support in helm chart

example:
values.yaml:
```
# -- Run the controller on the host network
hostNetwork: false

```
deployment.yaml:
```
spec:
  template:
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
```
